name: TestPlugin
version: ${project.version}
main: io.github.l1ttle_org.sampleplugin.SamplePlugin
api-version: 1.13
authors: [ l1ttle ]
description: Ping, pong!
website: https://github.com/l1ttle-org/SamplePlugin

commands:
  nick:
    description: Tests if the sender has a permission
    permission: testplugin.testperm
    permission-message: You do not have permission to use this command!
    usage: /<command> <player> <permission>

permissions:
  testplugin.testperm:
    description: Allows execution of /testperm command
    default: op
  testplugin.*:
    description: Wildcard permission
    default: op
    children:
      testplugin.testperm: true
